services:
  kibana:
    container_name: kibana
    hostname: kibana
    image: kibana:8.19.0
    restart: always
    ports:
      - "5601:5601"
    volumes:
      - ./data/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - elasticsearch.hosts=http://192.168.200.157:9200
