services:
  elasticsearch:
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - "./data/data:/usr/share/elasticsearch/data"
      - "./data/backup:/usr/share/elasticsearch/backup"
      - "./data/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    image: elasticsearch:8.19.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elasticsearch-password
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xlog:disable -Xlog:gc=debug:stderr -Xms512m -Xmx512m
    labels:
      createdBy: "Apps"
  kibana:
    container_name: kibana
    hostname: kibana
    image: kibana:8.19.0
    restart: always
    ports:
      - "5601:5601"
    volumes:
      - /data/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    depends_on:
      - elasticsearch
