spring:
  application:
    name: es-study
  elasticsearch:
    uris: http://192.168.200.157:9202
    connection-timeout: 1s
    socket-timeout: 30s
    username: elastic
    password: Elastic_rmRJXK
logging:
  level:
    tracer: TRACE
